name: Daily Standing Message

on:
  schedule:
    - cron: "0 4 * * Tue"   # Mondays 23:00 CT (CDT -> UTC 04:00 Tue)
    - cron: "0 4 * * Fri"   # Thursdays 23:00 CT (CDT -> UTC 04:00 Fri)
    - cron: "30 19 * * Sun" # Sundays 14:30 CT (CDT -> UTC 19:30 Sun)
    - cron: "0 23 * * Sun"  # Sundays 18:00 CT (CDT -> UTC 23:00 Sun)
    - cron: "0 3 * * Mon"   # Sundays 22:00 CT (CDT -> UTC 03:00 Mon)
  workflow_dispatch:
    inputs:
        webhook:
            description: 'Discord'
            required: true
            default: WonderPals
            type: choice
            options:
            - Test
            - Jonas Lolo

jobs:
  daily-message:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Get schedule
        id: get_schedule
        run: |
          # call your getDailyData() and save to a file
          node -e "require('./src/football-bot').getStandings().then(d=>console.log(d)).catch(err=>{ console.error(err); process.exit(1); })" > schedule.txt
          # expose the file contents as a multiline GitHub Actions output
          echo "schedule<<EOF" >> $GITHUB_OUTPUT
          cat schedule.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Select enviorment
        run: |
          # read the webhook input (empty string for schedule runs)
          selection="${{ github.event.inputs.webhook }}"

          # fallback to WonderPals when no input was provided (cron run)
          if [ -z "$selection" ]; then
            selection="Jonas Lolo"
          fi

          if [ "$selection" = "Test" ]; then
            echo "DISCORD_WEBHOOK=${{ secrets.DISCORD_WEBHOOK_TEST }}" >> $GITHUB_ENV
          elif [ "$selection" = "Jonas Lolo" ]; then
            echo "DISCORD_WEBHOOK=${{ secrets.WEBHOOK_DISCORD_JONAS_LOLO }}" >> $GITHUB_ENV
          else
            echo "Invalid webhook option"
            exit 1
          fi    

      - name: Discord notification
        env:
            DISCORD_WEBHOOK: ${{ env.DISCORD_WEBHOOK }}
            DISCORD_USERNAME: Football Bot
        uses: Ilshidur/action-discord@master
        with:
          args: "${{ steps.get_schedule.outputs.schedule }}"